### ISSUE TITLE
Describe what file paths are and how to use them

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#12]
### Ticket: Describe What File Paths Are and How to Use Them

---

#### Summary

Learn the fundamentals of file paths in a Unix-like operating system and how to correctly navigate and specify them in various commands.

---

#### Description

- **Objective**: Understand file paths' concept, structure, and how they navigate the filesystem and specify locations for various operations.
  
- **Scope**: 
  - Types of file paths (Absolute vs. Relative)
  - Navigating file paths using commands like `cd,` `ls,` and more
  - Common symbols (`~`, `.`, `..`, `/`)
  - Best practices and potential pitfalls
  
---

#### Learning Tasks

1. **Types of File Paths**: 
  - Learn about absolute and relative paths and when to use each.
  
2. **Navigating File Paths**: 
  - Get hands-on experience with navigating directories using `cd` and inspecting them using `ls.`
  
3. **Common Symbols**: 
  - Understand the meaning of symbols like `~` for the home directory,. `` for the current directory, and `..` for the parent directory.
  
4. **Best Practices and Pitfalls**: 
  - Familiarize yourself with common best practices for specifying file paths and potential mistakes to avoid.

5. **Hands-on Practice**: 
  - Exercise 1: Navigate to your home directory using an absolute and a relative path.
  - Exercise 2: Use `..` and `` to move around directories.
  - Exercise 3: Create a directory and navigate it using a relative path.
  - Exercise 4: Use a full path to copy a file from one directory to another.
  
6. **Troubleshooting**: 
  - Learn to resolve common issues related to file paths, such as "No such file or directory."

---

#### Learning Goals

- Be able to navigate the filesystem using file paths confidently.
- Understand the difference between absolute and relative paths and when to use each.
- Gain proficiency in using common symbols for specifying paths.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Ex 1

rel path to home dir: cd~ 

absolute path to home dir: cd /home

Ex 2

using cd .. will bring you 1 level up in the directory ie if you were at /something/different/apple and you used cd .. you would then be in the directory /something/different

using backticks is for creating in instruction to evaluate whatever you type as a command

Ex 3

mkdir temp

cd ~/temp

Ex 4

cp test.txt ~/temp

Common problems:
more often then note you spelled the directory/file incorrectly or you didnt use the right path to get the desired directory. Like trying to go to  /temp if /temp isnt in the next subdirectory that you're currently in.

**Comment by tupleHunden** [comment]
Looks good to me, there are more edge cases like if you're developing on macOS but deploy to Linux as macOS has case sensitivity issues with path names in the file system, but it's rare you'll encounter an issue.
