### ISSUE TITLE
Monitor system health with `top` or `htop`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#14]
#### Summary

Learn how to monitor system health in real-time using `top` and `htop` on a Unix-like operating system. Gain insights into CPU, memory usage, running processes, and other system metrics.

---

#### Description

- **Objective**: Acquire the skills to effectively monitor system health, resources, and performance using `top` and `htop.`
  
- **Scope**: 
  - Introduction to `top` and `htop`
  - Key metrics displayed (CPU usage, memory, processes, etc.)
  - Using various flags and options for detailed views
  - Best practices for system monitoring
  
---

#### Learning Tasks

1. **Introduction to `top` and `htop`**: 
  - Learn the basics of `top` and `htop` and how they differ.
  
2. **Key Metrics**: 
  - Understand the key metrics displayed in both utilities, such as CPU usage, memory, running processes, and load averages.
  
3. **Using Flags and Options**: 
  - Familiarize yourself with various flags and options for sorting, filtering, and getting detailed views.
  
4. **Best Practices**: 
  - Dive into the best practices for effective real-time system monitoring.
  
5. **Hands-on Practice**: 
  - Exercise 1: Open `top` and identify the top 5 CPU-consuming processes.
  - Exercise 2: Use `htop` to sort processes by memory usage.
  - Exercise 3: Use flags in `top` to show only specific metrics.
  - Exercise 4: Use `htop` to kill a specific process.
  
6. **Troubleshooting**: 
  - Cover common issues that might occur while using `top` and `htop` and how to resolve them.

---

#### Learning Goals

- Develop the ability to monitor system health and performance effectively.
- To diagnose system issues, utilize the `top` and `htop` features.
- Implement best practices in real-time system monitoring.

---

#### Priority

- Medium

**Comment by stottj** [comment]
1
Top is an older command and comes preinstalled on linux distros. Htop is new and adds color/more interactive user interface.

CPU and Memory usage 
		
* Each bar [] represents a CPU core and colorful ticks | inside the bar represent the load. Blue means low priority process, green means normal(user) process, red means kernel process. 
* Below the CPU bars are memory (mem) and swap (swp) rows. Green means used memory pages, blue means buffer pages, ye.low means cache pages.

Tasks, system load averages, uptime

* Tasks are number of open processes on the systems. They are broken down into 3 values: total number of tasks on the machine, number of threads those tasks are broken up into, number of tasks currently running
* Load average is a measure of computational work performed by CPU. A CPU with 100% utilization has 1.0 load average, that also means a quad-core CPU with 100% utilization has a 4.0 load average. The three load average numbers represent the 1 min average, 5 min average and 15 min average
* Uptime just shows the total time since its last reboot

Process info

* PID: process ID number
* USER: process owner
* PRI: process priority by the kernel
* NI: process priority reset by the user or root
* VIR: virtual memory process is consuming
* RES: physical memory process is consuming
* SHR: shared memory process is consuming
* S: current process state
* CPU%: percent of CPU processes is consuming
* MEM%: percent of memory process is consuming
* TIME%: time measure in clock ticks since process started
* Command: name of the command started the process


u: displays all processes owned by a specific user
p: sort process on high cpu consumption
m: sort process on high memory consumption
t: sort process on time
Space: tag a process
c:tag a prcoess and child processes
shift+u: remove all tags
shift+h:show/hide user/kernel process
a:set what CPU cores a process can access
i:set IO priority
h:help menu

Best practices are just ensuring that the processes that are being displayed are the ones you want to be using. Ensure your critical processes have the resources needed. Monitor to ensure that something non-critical is not taking all the resources you can provide. 

Ex1
WindowServer,firefox, appgate SDP, coreaudiod, top, music

Ex2
F6, M_Resident

Ex3
top -o cpu will display top with whatever process is using the most cpu as top.

Ex4
Select process+F9 to kill

**Comment by tupleHunden** [comment]
Looks good to me.  I rarely use `top` or `htop`, but it is nice to know they exist.  I've used `htop` a couple times at work but generally it's whenever I make a mistake server side and need to see what process is eating all of the resources.
