### ISSUE TITLE
Check network connectivity using `ping`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#16]
#### Summary

Learn how to use the `ping` command to check network connectivity between your local machine and another network device or website. Understand how `ping` works and how to interpret its output for basic network troubleshooting.

---

#### Description

- **Objective**: Acquire the skills to use `ping` to check network connectivity, diagnose network issues, and understand latency.
  
- **Scope**: 
  - Basic usage of `ping`
  - Understanding `ping` output
  - Practical use cases and best practices
  
---

#### Learning Tasks

1. **Understanding `ping`**: 
  - Learn what `ping` is, how it works, and why it is used for network diagnostics.
  
2. **Basic Usage of `ping`**: 
  - Get familiar with the syntax of the `ping` command and its primary usage for checking connectivity to a domain or IP address.
  
3. **Understanding `ping` Output**: 
  - Understand how to interpret the output of `ping,` including latency and packet loss.
  
4. **Practical Use-cases and Best Practices**: 
  - Discuss common scenarios where `ping` is helpful and best practices for its usage.
  
5. **Hands-on Practice**: 
  - Exercise 1: Use `ping` to check connectivity to a well-known website like `www.google.com.`
  - Exercise 2: Use `ping` with an IP address to diagnose connectivity.
  - Exercise 3: Interpret the output of a `ping` command to identify latency and packet loss.
  
6. **Troubleshooting**: 
  - Explore common issues you might encounter while using `ping` and their solutions.

---

#### Learning Goals

- Master the ability to check network connectivity using `ping.`
- Understand how to interpret the output of a `ping` command for troubleshooting purposes.
- Apply best practices for using `ping` in various networking scenarios.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Ex 1

When you ping www.google.com you will see if your computer can connect to google's server. If you dont receive a timeout error than that means you have internet connectivity.

Ex 2

You can ping a specific IP address to see if you connectivity as well. You will notice that when you pinged google.com it sent you to the closest google server, in my case that was 142.250.190.110. If I had used the command ping 142.250.190.110, it would have been the same as ping google. You can also ping other items/servers such as your router to see if you get a response. Helping on determining where your issues are for connectivity.

Ex 3

When I pinged google.com (or 142.250.190.110) I constantly received info. By telling ping to stop I received information on how many packets were transmitted to the loc and how many i received back. This will determine the packet loss. I also receive info on the min/avg/max/stddev which will help you determine what your latency is.

**Comment by tupleHunden** [comment]
👍🏻
