### ISSUE TITLE
Monitor system processes using commands like `ps`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#18]
#### Summary

Learn how to monitor system processes and gain insights into your system's operation using the `ps` command. Process management is crucial for system administration, debugging, and performance tuning.

---

#### Description

- **Objective**: Become proficient in using the `ps` command to monitor, analyze, and manage system processes.
  
- **Scope**: 
  - Introduction to process management
  - Understanding the `ps` command
  - Interpreting `ps` output
  - Practical use cases and best practices
  
---

#### Learning Tasks

1. **Introduction to Process Management**: 
  - Understand what a process is and why monitoring processes is essential.
  
2. **Understanding the `ps` Command**: 
  - Learn about the `ps` command, syntax, and options for displaying process information.
  
3. **Interpreting `ps` Output**: 
  - Understand how to read and interpret the output of the `ps` command for insights into running processes.
  
4. **Practical Use-cases and Best Practices**: 
  - Explore scenarios where the `ps` command can be handy and learn best practices for its usage.
  
5. **Hands-on Practice**: 
  - Exercise 1: Use `ps` to list all processes running for the current user.
  - Exercise 2: Use `ps` with flags like `-e,` `-f,` or `-l` to display extended process information.
  - Exercise 3: Identify a specific running process by its name or ID using `ps` and `grep.`
  
6. **Troubleshooting**: 
  - Examine common issues that may arise while using `ps` and how to resolve them.

---

#### Learning Goals

- Master the ability to monitor and analyze system processes using the `ps` command.
- Understand the critical aspects of process management and how to interpret `ps` output for system insights.
- Apply best practices for using `ps` in different debugging and performance tuning scenarios.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Monitoring processes are important as this could show you that you have programs using all the cpu/memory etc. And if you get lucky you might be able to spot malware running in the background.

ps commands has many different options. One would use ps -Option. For example ps -ef will show all running processes with full data about every process (probably not a great idea). ps -U userName is better as this would allow you to filter by user. If you know the process id you're looking for ps -p PID is the goto.

One could use the -o option to create user-specified output appearance, like renaming columns. ps -e -o pid=Process, ruser=RealUser, comm=Command. This makes things easier to read from the top for a new user.

Ex 1

ps -u username

Ex 2

As stated above ps -ef will show everything in a format listing.

ps -L PID will show the thread of that particular process

Ex 3
ps -e | grep -m1 firefox | awk '{awk $1}' will return with the PID of firefox

Common issues are incorrect spelling, not using the correct options, poor syntax

**Comment by tupleHunden** [comment]
👍🏻
