### ISSUE TITLE
Get system information using various commands

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#19]
### Ticket: Get System Information Using Various Commands

---

#### Summary

Learn how to use various commands to retrieve system information on a Unix-like operating system. Get insights into CPU, memory usage, disk space, and other system metrics.

---

#### Description

- **Objective**: Acquire skills to fetch different types of system information using command-line tools.
  
- **Scope**: 
  - Basic commands like `uname,` `df,` `free,` and `top.`
  - More advanced tools like `htop,` `lscpu,` and `lsmem.`
  - Interpretation of the output
  - Best practices and use cases
  
---

#### Learning Tasks

1. **Basic System Information**: 
  - Learn to use `uname` for getting basic system information like OS type, kernel version, etc.
  
2. **Disk Usage**: 
  - Understand how to check disk usage using the `df` command.
  
3. **Memory Usage**: 
  - Get familiar with the `free` command for memory-related information.
  
4. **Real-time Metrics**: 
  - Introduce yourself to `top` for real-time system metrics.
  
5. **Advanced Tools**: 
  - Dive into more detailed metrics using advanced tools like `htop,` `lscpu,` and `lsmem.`
  
6. **Interpreting Output**: 
  - Learn how to read and interpret the output from these commands.
  
7. **Hands-on Practice**: 
  - Exercise 1: Use `uname` to discover the kernel version.
  - Exercise 2: Check disk space using `df` and interpret the output.
  - Exercise 3: Run `free` to view available memory and swap space.
  - Exercise 4: Open `top` and identify the most CPU-intensive process.
  
8. **Troubleshooting**: 
  - Explore common issues that might arise and how to troubleshoot them.

---

#### Learning Goals

- Fetch and interpret essential system information using a variety of commands.
- Understand where and how to use different tools for different metrics.
- Interpret system metrics to make informed decisions.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Ex 1
uname -v, which gave me Darwin Kernel V 22.6.0

Ex 2
df -h, shows how much disk usage on a mounted filesystem.

Ex 3 free -h will show you the memory not being used for anything, aka wasted memory. Available memory is used for new or existing processes, this memory can be used without swapping.

Ex4 we've already touched top in the top/htop section. Using top command will show all the processes running sorted by current CPU usage for me a quick look showed Appgate SDP.

common issues are wrong usage of options/spelling mistaks, syntax mistakes.

**Comment by tupleHunden** [comment]
👍🏻
