### ISSUE TITLE
Write a paragraph comparing CLI and GUI

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#2]
#### Summary
Write a concise yet informative paragraph comparing the Command Line Interface (CLI) and Graphical User Interface (GUI) regarding their features, use cases, and limitations.

#### Description
- Objective: To articulate CLI and GUI's fundamental differences and similarities, touching on their advantages and disadvantages.
- Scope: Include speed, versatility, ease of use, learning curve, and resource consumption.

#### Tasks
1. Research the characteristics, features, and limitations of CLI.
2. Research the characteristics, features, and limitations of GUI.
3. Identify specific scenarios where one might be preferred over the other.
4. Draft a paragraph that encapsulates this information clearly and understandably.

#### Acceptance Criteria
- The paragraph should be between 150-200 words.
- Accurate representation of CLI and GUI features, pros, and cons.
- Include at least one example for each (CLI and GUI) where they shine or falter.

#### Priority
- Medium

**Comment by stottj** [comment]
# Compare CLI and GUI

Command line interfaces (CLI) exists today as more complicated way to get tasks done by a user on a device. With command line you need to know the exact commands you wish to execute and what the results will be as everything is displayed as a in depth word doc. But this also allows an individual to create scripts which are a preplanned list of instructions that the device will implement in order if everything is spelled correctly. With CLI you have a low cost of resources needed to perform the actions you want, and commands are executed much faster than their Graphical User Interface (GUI) counterpart.  More tech savvy individuals prefer CLI as they tend to know what they want and how to get it implemented and with CLI these tasks are performed at a much higher speed. GUIs on the other hand allow for a better user experience as it allows for more hand holding from providing alerts that drag users’ attention to problems to common icons that most individuals have seen before. But with this ease of usability comes with more resources needed to perform the same actions.

**Comment by tupleHunden** [comment]
Looks good to me 👍🏻 There are `TUI` applications these days built with frameworks like https://github.com/charmbracelet/bubbletea which make the terminal a much more graphical experience, but most of the time yeah it's just text dumped to `stdout`
