### ISSUE TITLE
View a large text file using `cat`, `less`, and `more`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#20]
### Summary

Learn how to view the contents of large text files using command-line utilities like `cat,` `less,` and `more.` These utilities make navigating, searching, and reading files directly from the command line easier.

---

#### Description

- **Objective**: Understand how to efficiently view and navigate through large text files in a terminal using `cat,` `less,` and `more.`
  
- **Scope**: 
  - Introduction to `cat`
  - Introduction to `less`
  - Introduction to `more`
  
---

#### Learning Tasks

1. **Introduction to `cat`**: 
  - Learn what the `cat` command does and when it's most effective.
  
2. **Introduction to `less`**: 
  - Get to know the `less` command, its navigation features, and why it's useful for large files.
  
3. **Introduction to `more`**: 
  - Understand the `more` command and how it differs from `less.`
  
4. **Hands-on Practice**: 
  - Exercise 1: Use `cat` to display the content of a small text file and understand its limitations with large files.
  - Exercise 2: Open a large text file with `less` and practice navigation keys (`g` for top, `G` for bottom, `/` for search).
  - Exercise 3: Open the same large text file with `more` and notice the differences in navigation and features.
  - Exercise 4: Compare the speed and usability of `cat`, `less,` and `more` for large files.
  
5. **Troubleshooting**: 
  - Discuss common issues like terminal freezing or excessive memory usage when dealing with large files and how to mitigate them.

---

#### Learning Goals

- Gain a strong understanding of the utilities available for viewing large text files.
- Become proficient in navigating and searching within files using `less` and `more.`
- Understand the limitations of `cat` for large files and when to use each utility for optimal performance.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Ex 1. Cat is short for concatenate, this command displays the contents of 1 or more files without having to open the file for editing. Cat is best used on smaller files (cat test.txt will show what is in the text file test), if it is used on larger files you will end up with huge string of data that's hard to read. You can use more to break it into pages. 

Ex 2 less test.txt will allow you move around in the file by using the arrow keys to move horizontal and vertical. Less also doesnt load the entire document at the start so it will spin up quickly.

Ex 3 more test.txt will allow you to scroll the contents of the file by using the enter key, one line at a time. If you wish to scroll by page the space bar will fill that function.

ex 4 as stated above, using a cat on a large file will display everything but will not stop till it gets to the last screen worth of content. With more you can proceed through the file but it will read the entire thing before running. Less will allow you to do the same as more but will only read the current content as needed.

Terminal freezing can happen if you try to load a way to large file and the program. Using less will help.

**Comment by tupleHunden** [comment]
👍🏻
