### ISSUE TITLE
Edit a text file using nano, vi, or emacs

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#21]
#### Summary

Get hands-on experience editing text files using command-line text editors: `nano,` `vi,` and `emacs.` Each editor has its features and shortcuts, and knowing how to use them can significantly enhance your productivity in the terminal.

---

#### Description

- **Objective**: Learn how to edit text files effectively using `nano,` `vi,` or `emacs` from the command line.
  
- **Scope**: 
  - Introduction to `nano`
  - Introduction to `vi`
  - Introduction to `emacs`
  
---

#### Learning Tasks

1. **Introduction to `nano`**: 
  - Familiarize yourself with `nano,` a beginner-friendly, straightforward text editor.
  
2. **Introduction to `vi`**: 
  - Dive into `vi,` a powerful text editor with a steep learning curve.
  
3. **Introduction to `emacs`**: 
  - Get to know `emacs,` a text editor that is highly extensible and feature-rich.
  
4. **Hands-on Practice**: 
  - Exercise 1: Open a text file using `nano` and practice basic editing tasks like adding text, deleting, and saving changes.
  - Exercise 2: Open the same text file using `vi` and learn to navigate in normal insert modes and save changes.
  - Exercise 3: Open the text file with `emacs` and explore its editing and navigation features.
  - Exercise 4: Compare the three editors regarding ease of use, features, and speed.
  
5. **Troubleshooting**: 
  - Discuss common issues and solutions when using these text editors, such as modes in `vi` or keybindings in `emacs.`

---

#### Learning Goals

- Become familiar with `nano,` `vi,` and `emacs` for text editing.
- Gain practical experience in editing text files using these editors.
- Understand the pros and cons of each editor and identify which suits your needs best.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Ex 1 % nano test.txt to open file. With nano you can start typing and editing the text immediately. You can delete with the simple backspace button. To save changes its ctrl+o and then ctrl+x to exit.

Ex 2 vim test.txt to open file. With vim to modify you have to change into insert mode with a or i. once you made your changes you have to move back to normal mode with the esc key. once this is done you can save your file by using :w. If you wanted to save and exit use :x. :q to quit without saving and :q! if you had a change you wanted discarded.

Ex 3 emacs, on mac at least, had two different ways to opening it. Once installed with brew it created an emac app incase you didnt feel like opening this through a terminal. After opening up emacs app you get a typical gui window. It uses a lot of convential items for showing what button you need to push to save, open a file, create a new file, etc. Once you're done modifying a file you can exile close it. If you opened emacs via terminal you get the typical commands on how to use it. Once again it's like vim where you need to know the commands once you go past the initial help page.

Ex 4. Out of the three editors I would say the easist to use was emacs (you could use emacs -nw to bring up a text box style). It uses a GUI system which allows for basic and easy to understand icons for what you would like to do. Next for me nano, it was pretty easy to open up, it showed you how to perform quick actions you wanted at the bottom of the text screen. After nano using the terminal emacs it starts to raise the difficulty as a newbie. You have special commands you need to know to open/close etc. Not know these commands Last was vim, it's not intuitive to escape out of the different modes, also you need to know the commands you are trying to do before hand. But once you know how to use vim you look like a space wizard.


Common issues with vim not know how to exit what your doing properly. To edit a file you have to perform a special key action which will let you modify it even though when you pull up the file it makes you think you can start modifying it right away. Then making sure you exited out of that mode before you can save. Or using the wrong exit if you ment to save and quit. Nano has the same thing where you could use the wrong key bindings if you're not paying attention but at least you can see what keybind you need to use at the bottom of the screen.

**Comment by tupleHunden** [comment]
👍🏻 vim 💯
