### ISSUE TITLE
Search text within a file using `grep`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#22]
#### Summary

Learn to use `grep` for searching text within files. `grep` is a powerful command-line utility that lets you search through one or multiple text files for lines that match a regular expression pattern.

---

#### Description

- **Objective**: Master `grep` to search for specific text within a file, making it easier to analyze or filter data.
  
- **Scope**: 
  - Introduction to `grep`
  - Basic to advanced searching techniques with `grep`
  
---

#### Learning Tasks

1. **Introduction to `grep`**: 
  - Get familiar with' grep' and its basic syntax for searching text in files.
  
2. **Basic to Advanced Searching Techniques**: 
  - Learn to perform basic text searches and then move on to more advanced techniques like using regular expressions.
  
3. **Hands-on Practice**: 
  - Exercise 1: Use `grep` to search for a specific word in a text file.
  - Exercise 2: Use `grep` with flags to ignore case (`-i`) or to search recursively (`-r's).
  - Exercise 3: Perform a more complex search using regular expressions.
  - Exercise 4: Pipe the output of another command into `grep` to filter it.
  
4. **Troubleshooting**: 
  - Discuss common issues one might encounter when using `grep` and how to solve them.

---

#### Learning Goals

- Develop a thorough understanding of how `grep` works.
- Become proficient in using `grep` for various text-searching tasks.
- Understand the utility of `grep` in real-world scenarios like log analysis or data filtering.

---

#### Priority

- Medium

**Comment by stottj** [comment]
rep consists of 3 items. Starts with grep, followed by the string you are searching for and then the file name to search in: grep string filename

You can do multiplefiles as well: grep string filename filename filename

If you want to search in all files of the directory its grep string *

Common options for grep:

* -w whole words only
* -i ignore case
* -r will include subdirectories
* -v will include all lines that do not match a specific string
* -x will show lines that exactly match
* -l will show names of the files
* -c count the number of matches

Ex 1. grep file test.txt (shows this is a test file i am updating.)

Ex 2. grep -i more test.txt (shows more changes, more test)

Ex 3. grep -n -C 1 test test.txt (displays the line before and after match, also shows line numbers)

Ex 4. ls -l | grep rwx (this allows you to see an item that any one has full read, write, execute access.

Common problems with grep are, forgetting to specify a file name. Also note case sensitivity, there's a reason why they included -i option. Also make sure you are in the right directory for the item you are searching for.

**Comment by tupleHunden** [comment]
👍🏻 - These days I'd suggest using `ripgrep` over `grep`
