### ISSUE TITLE
List the advantages of using CLI over GUI

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#3]
#### Summary
Compile a comprehensive list of advantages that make Command Line Interface (CLI) a more effective option than Graphical User Interface (GUI) for specific tasks or in certain scenarios.

#### Description
- Objective: To document the key strengths of CLI over GUI in order to inform decision-making for tool selection, project development, or educational content.
- Scope: Focus on the tangible benefits such as performance, resource usage, and specific use-cases where CLI has a clear edge.

#### Tasks
1. Research performance benefits of CLI:
    - Speed
    - Resource consumption
    - Task automation
2. Investigate versatility:
    - How CLI can manage complex tasks with simple commands
    - Batch processing capabilities
3. Examine user control:
    - Granularity of control provided by CLI
    - Capability to perform tasks not possible or too cumbersome in GUI
4. Review community and documentation:
    - Availability of open-source CLI tools
    - Robustness of documentation and community support
5. Compile this information into a well-organized list or report.

#### Acceptance Criteria
- A detailed list or report that fulfills all tasks mentioned.
- Include real-world examples or case studies to substantiate each advantage.
- Ensure information is factual and sourced from credible references.

#### Priority
- Medium

**Comment by stottj** [comment]
Due to the fact that CLI is all text it requires a lot less resources for usage. Removing such requirements also allows CLIs to be performed on a low res monitor and with a slower processor. You dont need to install large programs such as windows as most all OS support CLI. CLI also helps with easy to implement automation as one can create a script before hand and then implemented with a single command.

Scripts can be as indepth as needed. These programs are created before hand then used wherever. A script could be used to implement hundreds of changes. And with a script you have a base standard that could be used with 1 command over many devices.

One can create batch processing to perform scripts at certain times, usually off-peak. Batch processing is a high-volume, repetitve data job such as backups/sorting.

CLI provides access control by allowing for creation of multiple user accounts for whatever level is needed. Such as setting of Admin role wich will have ability to perform a large amount of tasks to a user role wich will allow functionality needed to perform a smaller scope task.

**Comment by tupleHunden** [comment]
Looks good to me 👍🏻 One major advantage is also full access to the GNU software if you're on a unix system.  https://www.gnu.org/software/parallel/ or https://httpd.apache.org/docs/2.4/programs/ab.html are fantastic for writing tools and it's all done in the terminal.
