### ISSUE TITLE
Explain the difference between a terminal and a shell

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#4]
#### Summary
Clarify the distinction between a terminal and a shell, focusing on their roles, functionalities, and interactions within an operating system.

#### Description
- Objective: To create straightforward, factual content that delineates the roles and functionalities of a terminal and a shell. This information will serve for educational purposes, documentation, or development.
- Scope: Include key terms, historical context if necessary, and specific use cases or examples to illustrate the differences.

#### Tasks
1. Research the function and history of the terminal:
    - What is a terminal?
    - What roles does it fulfill?
    - Types of terminals (e.g., hardware terminal, terminal emulator)
2. Research the function and history of the shell:
    - What is a shell?
    - Types of shells (e.g., Bash, Zsh, PowerShell)
    - What roles does it fulfill?
3. Investigate the interaction between terminal and shell:
    - How do they communicate?
    - How are they dependent or independent of each other?
4. Compile this information into a clear and concise explanatory text or report.

#### Acceptance Criteria
- A well-structured text or report that addresses all the tasks.
- Use real-world examples or analogies to clarify the distinctions.
- Ensure all statements are factual and supported by credible sources.

#### Priority
- Medium

**Comment by stottj** [comment]
A terminal is the area that a user will interact with. It takes input from the user in the forms of commands and relay whatever output on the screen. It is the input-output device for the user. Terminals used to be actual hardware that was part of the computer. Nowdays terminals are software program. Once the user inputs a command we move on to the shell.

Shell is a different program that interprets the commands given by the user. If the commands are correct it will convert the commands into a kernel-understandable form and pass them onwards. Once the command is done a prompt will display on the terminal showing it is ready for the next command.

There are different types of shells which fullfill different needs. 

* C Shell provides build in arethmetic and C-Like expressions.
* Bourne shell lacks features for interactive use like recall previous commands but is very fast.
* GNU Bourn-Again Shell is compatible to bourne but includes featers from Korn and Bourne shell.
* Z shell is an extended version of bash with more features and capabilities

**Comment by tupleHunden** [comment]
Looks good to me 👍🏻
