### ISSUE TITLE
Explore and list 3 popular terminal emulators

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#5]
#### Summary

Explore and document three popular terminal emulators' features, benefits, and limitations. The objective is to understand their functionalities and critical differences.

---

#### Description

- **Objective**: To provide a comprehensive overview of three popular terminal emulators for knowledge sharing, comparison, or potential adoption.
  
- **Scope**: 
  - Features that set them apart
  - Benefits in terms of performance, customization, etc.
  - Limitations or drawbacks

---

#### Tasks

1. **Identify 3 Popular Terminal Emulators**: Pick three widely-used terminal emulators for exploration.

2. **Research Features**: 
  - Identify and document the unique features of each emulator.
  
3. **Assess Benefits**: 
  - Investigate the advantages or strengths each offers. Look into aspects like speed, user-friendliness, and customization options.

4. **Note Limitations**: 
  - List any significant limitations or downsides.

5. **Compile Information**: 
  - Consolidate the findings into a markdown document.

---

#### Acceptance Criteria

- A markdown file that addresses all the above tasks.
- Inclusion of factual information with supporting evidence or citations where applicable.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Popular terminal emulators:

* Guake Terminal: Terminal created for Gnome. Opens with a hotkey from the top of a screen, freeing up monitor space till needed. Can configure tabs naming for quick usage. Though sometimes it does have issues with responsiveness.
* Terminus: Designed with SSH sessions in mind. Runs on various platforms and helps with the complexities of SSH client requirements across the different OS. Has advenced features like port forwarding and SFTP support. But terminus does have a subscription model and it is very intense for beginners.
* iTerm2: specficully designed for macOS, providing features not found on default app. Allows for split panes, hotkey windows and search functionality. Aids with auto-suggestion and tracks command history. One big con is it being mac only, also requires manual updates as its not found on the App Store.

**Comment by tupleHunden** [comment]
iTerm2 is nice, most folks at work use it.  

Looks good to me 👍🏻
