### ISSUE TITLE
Write a summary on different shell types (Bash, Zsh, Fish, Dash)

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#6]
### Ticket: Write a Summary on Different Shell Types (Bash, Zsh, Fish, Dash)

---

#### Summary

Compose a comprehensive summary that explores the characteristics, functionalities, and distinctions among four different shell types: Bash, Zsh, Fish, and Dash.

---

#### Description

- **Objective**: To inform and educate about the differences among these shell types, highlighting their unique features, advantages, and use cases.
  
- **Scope**: 
  - Core functionalities
  - Features that make each shell unique
  - Advantages and disadvantages
  - Popular use cases for each

---

#### Tasks

1. **Research Bash**: 
  - Identify core functionalities and unique features.
  - Note any advantages or disadvantages.
  
2. **Research Zsh**: 
  - Identify core functionalities and unique features.
  - Note any advantages or disadvantages.

3. **Research Fish**: 
  - Identify core functionalities and unique features.
  - Note any advantages or disadvantages.

4. **Research Dash**: 
  - Identify core functionalities and unique features.
  - Note any advantages or disadvantages.

5. **Compile Information**: 
  - Summarize the findings in a concise but informative document.

---

#### Acceptance Criteria

- A document that covers all the tasks mentioned, providing a well-rounded view of each shell type.
- Factual accuracy is necessary, and citations or references should be included where applicable.

---

#### Priority

- Medium

**Comment by stottj** [comment]
Bash is the most common linux shell. Can create aliases, make functions, export vars, run commands. Cant automatically change the directory name. Also Bash does not have an inline wildcard expression.

Zsh is faster and more customizable than bash. Includes spell correction, sharing command history across terminals, naming directory shortcuts. With autocompletion you have to activiate it with tab button, this provides a drop-down providing other possible files/dirs. Zsh is also much more configurable than Bash as it supports plugins and themes.

Fish is based on interactivity and usability. Fish has a lot already preconfigured which makes it a bit easier for new users. Fish comes with a search as you type automatic suggestions feature based on command history and dir you're in. But that means search history is always on. Features are prefered as commands rather than syntax. 

Dash has a very fast startup time and is low memory usage. This also means that it has no support for shell specific extensions that are not part of POSIX standards. Dash is also the default shell for Debian systems. One issue is if you're used to Bash, Dash does not support all of bash features.

**Comment by tupleHunden** [comment]
👍🏻
