### ISSUE TITLE
Navigate to different directories using `cd`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#7]
### Ticket: Navigate to Different Directories Using `cd`

---

#### Summary

Create a guide or tutorial demonstrating how to navigate different directories using the `cd` command in the command-line interface.

---

#### Description

- **Objective**: To educate users on effectively using the `cd` command for directory navigation in a Unix-like operating system.
  
- **Scope**: 
  - Basic usage of `cd`
  - Advanced options and flags
  - Common use cases and scenarios
  - Troubleshooting common issues

---

#### Tasks

1. **Basic Usage**: 
  - Explain the simplest form of `cd` and how it works.
  
2. **Advanced Options**: 
  - Cover any flags or options that can be used with `cd.`
  
3. **Common Scenarios**: 
  - Demonstrate how to navigate to parent directories and home directories using relative vs. absolute paths.

4. **Troubleshooting**: 
  - List common issues users might face and how to solve them.

5. **Compile Information**: 
  - Create a guide or tutorial that encapsulates all the above information.

---

#### Acceptance Criteria

- A well-structured guide or tutorial that covers all the listed tasks.
- Include examples and screenshots where applicable.
- Factual accuracy is essential.

---

#### Priority

- Medium

**Comment by stottj** [comment]
CD or change directory command allows you to manipulate where you are currently at in your directories. For instance cd Documents will put you in the Document subdirectory.

Using the / argument with cd allows you change the directory to the root directory. 
Using the ~ argument with cd allows you to change the directory to the home directory from any loc in linux system.

Using the .. argument with cd allows you to move up 1 lvl from the current directory.

When you change directories you can use absolute or relative path names. The absolute path starts from system root / while relative path starts from your current directory. If documents exists in your home directory you can get there by cd Documents which is a relative path to the directory. If you wanted to go to documents using absolute you would use cd /home/username/Documents.

Some common issues one might see using cd is if you get path is not found make sure you're spelling it correctly. If you did spell the path correctly make sure the path you want is there, use mkdir to create the path if it isnt there.

**Comment by tupleHunden** [comment]
👍🏻
