### ISSUE TITLE
List directory contents with `ls`

### ISSUE THREAD

**Issue by stottj** [stottj/Command-Line#8]
### Ticket: List Directory Contents with `ls`

---

#### Summary

Develop a guide or tutorial to educate users on how to list directory contents using the `ls` command in a Unix-like operating system.

---

#### Description

- **Objective**: Provide a comprehensive understanding of the `ls` command, focusing on various options and use cases.
  
- **Scope**: 
  - Basic `ls` command usage
  - Common options and flags
  - Use cases for sorting, filtering, and displaying additional information
  - Troubleshooting

---

#### Tasks

1. **Basic Usage**: 
  - Describe the basic functionality of the `ls` command and its most straightforward use cases.
  
2. **Common Options**: 
  - Explain their purposes and benefits by exploring commonly used flags such as `-l,` `-a`, `-h,` etc.

3. **Sorting and Filtering**: 
  - Show how to use `ls` to sort files by date, name, or other attributes and filter files based on specific criteria.
  
4. **Additional Information**: 
  - Explain how to display additional file details like permissions, date modified, and more.

5. **Troubleshooting**: 
  - Address common issues users may encounter while using `ls` and provide solutions.

6. **Compile Information**: 
  - Create a well-organized guide or tutorial incorporating all the above points.

---

#### Acceptance Criteria

- A clear and informative guide or tutorial with examples, even screenshots, to aid understanding.
- All information must be factual and accurate.

---

#### Priority

- Medium

**Comment by stottj** [comment]
ls is a shell command that lists directory info of files/directories. You can use options to gain more insight or provide specific commands.

Option -l which will display detailed information of files/directories such as showing the permissions/files owner/size/creation date and time.

Option -a will show everything in the listing including hidden files and directories

Option -h will provide file sizes in a more easier to understand format

Option -d will only list directories

To sort by last modified one would use ls -lt

To sort by largest size first one would use ls -lS

To sort by name one would use ls -l
Note it will sort in the following order: . .. numbers upercaseletters lowercaseletters

Common problems that arise with using ls:

    if there are too many files when uses ls the system might get bogged down. One way to help prevent this is to make sure coloring is turned off by --color=never. Also make sure sorting is not happening by using ls -U.
    if a command is not working when you think it should make sure to check for typos.

**Comment by tupleHunden** [comment]
👍🏻
